<h4 class='prehead'>SM286D &middot; Introduction to Applied Mathematics with Python &middot; Spring 2020 &middot; Uhan</h4>

<h1 class='lesson_title'>Final Exam &mdash; Review Problems &mdash; Part I &mdash; Solutions</h1>

## Problem 1

In [1]:
l = range(4)
for i in l:
    print(i)

0
1
2
3


## Problem 2

In [2]:
x = 1
for i in range(2,5):
    if x < 3:
        x = 2 * x
    elif x < 4:
        x += 1
    else:
        x -= 3
print(x)

1


## Problem 3

In [3]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [0, 1]])

print(A * B)  # This multiplies entry wise.
print(A ** B)  # This take powers entry wise.
print(A.dot(B))  # Correct
print(np.matmul(A,B))  # Also, correct.

[[1 2]
 [0 4]]
[[1 2]
 [1 4]]
[[1 3]
 [3 7]]
[[1 3]
 [3 7]]


## Problem 4

In [4]:
L = []
for i in range(11):
    L.append(2 ** i)
    
L[1:10:2]  
# L[1:9:2]
# L[0:10:1]
# L[1:10:1]

[2, 8, 32, 128, 512]

## Problem 5

In [5]:
n = 0
while True:
    if n < 0:
        break
    elif n < 2021:
        n = n ** 2
    else:
        n -= 2019
print(n)

# Press the stop button to get out of this infinite loop!

KeyboardInterrupt: 

## Problem 6

In [6]:
import numpy as np

def func(x, y):
    a = x ** 2 + y ** 3
    b = x - 4 * y
    return [a, b]

func(2, 1)

[5, -2]

## Problem 7

In [7]:
n = input("How old are you? ")

try:
    if n < 40:
        print("Wow you look great.")
    else:
        print("Maybe you should exercise more.")
except TypeError:
    print("Please enter a numerical value for your age.")

How old are you? 22
Please enter a numerical value for your age.


## Problem 8

In [8]:
class Drive():
    """This class will document a long drive."""
    def __init__(self, distance):
        """Initialize the distance and weather in your drive."""
        self.distance = distance
    
    def duration(self):
        """This gives an approximation of the duration."""
        T = self.distance / 60
        return print(f"Your trip will take about {T} hours.")
    
D = Drive(150)
D.duration()

Your trip will take about 2.5 hours.
